#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create folders
mkdir -p \
    /config/cache
# create folders (COPS 3.x)
mkdir -p \
    /config/config

# copy config
if [[ ! -e /config/config/local.php ]]; then
    if [[ -e /config/config_local.php ]]; then
        echo "**** Existing config found, migrating for v3. Please check the contents of /config/config/local.php which will be the active config in v3 ****"
        cp /config/config_local.php /config/config/local.php
    else
        echo "**** New instance detected, generating default config at /config/config/local.php ****"
        cp /defaults/local/local.php /config/config/
    fi
fi

cp /defaults/config/* /config/config/

# permissions
lsiown -R abc:abc \
    /config
