#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    /config/cache

# clear previous config
for f in /app/www/public/config_local.*.php
do 
    if [ -f "$f" ]; then
        rm "$f"
    fi
done

# copy config
if [[ ! -e /config/config_local.php ]]; then
    cp /defaults/config_local.php /config/config_local.php
fi

# copy extra user-profiles
for f in /config/config_local*.php
do 
cp "$f" /app/www/public/
done

# permissions
chown -R abc:abc \
    /config \
    /app/www/public \
    var/www/localhost/cops
