#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/config/cache

# make symlink
[[ ! -e /var/www/localhost/cops ]] && \
	ln -s /usr/share/webapps/cops /var/www/localhost/cops

# clear previous config
for f in /var/www/localhost/cops/config_local.*.php
do
   # if file, delete it
   [ -f "$f" ] && rm "$f"
done

# copy config
[[ ! -e /config/config_local.php ]] && \
	cp /defaults/config_local.php /config/config_local.php

# copy extra user-profiles
[[ -e /config/config_local*.php ]] && \
   cp /config/config_local*.php /var/www/localhost/cops/

# permissions
chown -R abc:abc \
	/config \
	/usr/share/webapps/cops \
	var/www/localhost/cops
