#!/usr/bin/with-contenv bash

# install cops
if [ ! -e "/config/www/cops/index.php" ]; then
curl -o \
 /tmp/cops.tar.gz -L \
	"https://github.com/seblucas/cops/archive/${COPS_VER}.tar.gz"
mkdir -p \
	/config/www/cops
tar xf /tmp/cops.tar.gz -C \
	/config/www/cops --strip-components=1
fi

# copy config
[[ ! -e /config/www/cops/config_local.php ]] && \
	cp /defaults/config_local.php /config/www/cops/config_local.php

# permissions
chown -R abc:abc \
	/config/www
