#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo '
╔════════════════════════════════════════════════════╗
╠════════════════════════════════════════════════════╣
║                                                    ║
║             This image is deprecated.              ║
║      We will not offer support for this image      ║
║            and it will not be updated.             ║
║                                                    ║
╠════════════════════════════════════════════════════╣
╚════════════════════════════════════════════════════╝

COPS has been abandoned by its developers and no actively maintained forks exist at this time.

══════════════════════════════════════════════════════'
